A)
-- Error: SELECT * FROM I WHERE MODULO = NULL;
SELECT PROFESOR FROM D  WHERE PROFESOR NOT IN (SELECT DISTINCT PROFESOR FROM I);

B) SELECT PROFESOR FROM I GROUP BY PROFESOR HAVING COUNT(MODULO)=2;

C)
-- SELECT DEPARTAMENTO,COUNT(CICLO) AS
SELECT DEPARTAMENTO,COUNT(DISTINCT CICLO) AS  CICLOS
	FROM D
	JOIN I ON D.PROFESOR = I.PROFESOR
	JOIN E ON E.MODULO = I.MODULO
	GROUP BY DEPARTAMENTO
--	HAVING COUNT(CICLO) >1
	HAVING CICLOS > 1

Apartado d)

WITH MODULOSAPROBADOS AS(
	SELECT ALUMNO,COUNT(NOTA) AS APROBADOS
	FROM M
	WHERE NOTA>=5
	GROUP BY ALUMNO),
MODULOSTOTALES AS (
	SELECT ALUMNO,COUNT(MODULO) AS TOTALES
	FROM M
	GROUP BY ALUMNO)
SELECT A.ALUMNO
FROM MODULOSAPROBADOS AS A
JOIN MODULOSTOTALES AS B ON A.ALUMNO = B.ALUMNO
WHERE A.APROBADOS = B.TOTALES

Apartado e)

WITH MODULOSAPROBADOS AS(
	SELECT ALUMNO,COUNT(NOTA) AS APROBADOS
	FROM M
	WHERE NOTA>=5
	GROUP BY ALUMNO),
MODULOSTOTALES AS (
	SELECT ALUMNO,COUNT(MODULO) AS TOTALES
	FROM M
	GROUP BY ALUMNO),
MEDIAS AS (
	SELECT A.ALUMNO, AVG(C.NOTA) AS MEDIA
	FROM MODULOSAPROBADOS AS A
	JOIN MODULOSTOTALES AS B ON A.ALUMNO = B.ALUMNO
	JOIN M AS C ON A.ALUMNO = C.ALUMNO
	WHERE A.APROBADOS*2 >= B.TOTALES
	GROUP BY A.ALUMNO)
SELECT AVG(MEDIA) FROM MEDIAS